import json
import re

import httpx

from app.ai.providers.base import AIProvider
from app.ai.providers.mock_provider import MockAIProvider
from app.ai.schemas import AgentSuggestion
from app.config import settings
from app.enums import ActionType


class GeminiAIProvider(AIProvider):
    name = "gemini"

    def __init__(self) -> None:
        self.fallback = MockAIProvider()

    def suggest_actions_for_work_item(
        self,
        title: str,
        body: str,
        customer: str | None,
        priority: str,
    ) -> list[AgentSuggestion]:
        if not settings.gemini_api_key:
            return self.fallback.suggest_actions_for_work_item(title, body, customer, priority)

        prompt = build_prompt(title=title, body=body, customer=customer, priority=priority)

        try:
            raw_text = self._call_gemini(prompt)
            parsed = extract_json(raw_text)
            suggestions = suggestions_from_json(parsed)

            if not suggestions:
                return self.fallback.suggest_actions_for_work_item(title, body, customer, priority)

            return suggestions
        except Exception:
            return self.fallback.suggest_actions_for_work_item(title, body, customer, priority)

    def _call_gemini(self, prompt: str) -> str:
        url = (
            "https://generativelanguage.googleapis.com/v1beta/models/"
            f"{settings.gemini_model}:generateContent"
        )

        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "text": prompt,
                        }
                    ]
                }
            ],
            "generationConfig": {
                "temperature": 0.2,
                "responseMimeType": "application/json",
            },
        }

        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                params={"key": settings.gemini_api_key},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()

        return data["candidates"][0]["content"]["parts"][0]["text"]


def build_prompt(title: str, body: str, customer: str | None, priority: str) -> str:
    customer_name = customer or "customer"

    return f"""
You are OpsFlow AI, an enterprise workflow automation assistant.

Given one operational support item, return safe, structured, human-reviewable workflow actions.

Rules:
- Return only valid JSON.
- Do not include markdown.
- Do not include text outside JSON.
- Never directly execute an action.
- Every action must require human approval.
- Confidence must be between 0.0 and 1.0.
- Category must be one of: billing, bug, delivery, incident, feedback, general.
- action_type must be one of:
  draft_reply, create_task, escalate_issue, slack_alert, github_issue

Input:
Title: {title}
Body: {body}
Customer: {customer_name}
Priority: {priority}

Return JSON in this exact shape:
{{
  "category": "billing",
  "actions": [
    {{
      "action_type": "draft_reply",
      "title": "Draft customer reply for customer",
      "payload": {{
        "draft_reply": "message body here",
        "requires_human_review": true
      }},
      "explanation": "why this action is recommended",
      "confidence": 0.85
    }}
  ]
}}

Generate 1 to 4 useful actions.
Prefer:
- draft_reply for customer-facing issues
- escalate_issue for urgent or high-risk issues
- slack_alert for incidents or outages
- github_issue for engineering bugs
- create_task for internal follow-up
""".strip()


def extract_json(text: str) -> dict:
    cleaned = text.strip()

    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```json", "", cleaned, flags=re.IGNORECASE).strip()
        cleaned = re.sub(r"^```", "", cleaned).strip()
        cleaned = re.sub(r"```$", "", cleaned).strip()

    return json.loads(cleaned)


def suggestions_from_json(parsed: dict) -> list[AgentSuggestion]:
    category = str(parsed.get("category", "general")).lower()
    actions = parsed.get("actions", [])

    suggestions: list[AgentSuggestion] = []

    valid_action_values = {item.value for item in ActionType}

    for action in actions:
        raw_type = str(action.get("action_type", "draft_reply"))

        if raw_type not in valid_action_values:
            raw_type = "draft_reply"

        title = str(action.get("title", "AI suggested action"))[:255]
        payload = action.get("payload", {})

        if not isinstance(payload, dict):
            payload = {"value": str(payload)}

        explanation = str(action.get("explanation", "Generated by AI provider."))
        confidence = float(action.get("confidence", 0.75))

        payload["requires_human_review"] = True
        payload["ai_provider"] = "gemini"

        suggestions.append(
            AgentSuggestion(
                action_type=ActionType(raw_type),
                title=title,
                payload=payload,
                explanation=explanation,
                confidence=max(0.0, min(1.0, confidence)),
                category=category,
            )
        )

    return suggestions
